Repository DeveloperAcademy-POSTECH/MC3-Team2-Ddoongs, pull requests merged in 2022-07, with the labels that each got.

#8 Merge: "AddWordView UI 만들기"
  KBoard/KBoard.xcodeproj/project.pbxproj
  KBoard/KBoard/Controller/AddWordViewController.swift
Labels: 윌🌊

#9 Merge: "WordDetailView 상단Cell UI 만들기"
  KBoard/KBoard.xcodeproj/project.pbxproj
  KBoard/KBoard/Controller/WordDetailViewController.swift
  KBoard/KBoard/View/WordDetailViewUIComponent/WordDescriptionView.swift
Labels: 윌🌊

#13 Merge: "My Board(category list)" UI 구현 #6
  KBoard/KBoard.xcodeproj/project.pbxproj
  KBoard/KBoard/Controller/AddNewCategory.swift
  KBoard/KBoard/Controller/CategoryListViewController.swift
  KBoard/KBoard/Controller/CustomTableCell.swift
  KBoard/KBoard/Controller/ViewController.swift
  KBoard/KBoard/Model/KBoardDate.swift
  KBoard/KBoard/SupportFiles/Assets.xcassets/AppIcon.appiconset/Contents.json
  KBoard/KBoard/SupportFiles/SceneDelegate.swift
Labels: 노엘 😎

#17 Merge: #5 K-pop Slang - WordListView, WordCustomCell 제작
  KBoard/KBoard.xcodeproj/project.pbxproj
  KBoard/KBoard/Controller/DictionaryViewController.swift
  KBoard/KBoard/View/WordCustomCell.swift
  KBoard/KBoard/View/WordListView.swift
Labels: feat💥, 니로 🚘, UI🌉

#20 Merge: "create KeyboardUI"
  KBoard/CustomKeyboard/Info.plist
  KBoard/CustomKeyboard/KeyboardViewController.swift
  KBoard/KBoard.xcodeproj/project.pbxproj
  KBoard/KBoard/Controller/ViewController.swift
  KBoard/KBoard/SupportFiles/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: 진 😊

#22 Feat/6 my board(category list)UI
  KBoard/KBoard.xcodeproj/project.pbxproj
  KBoard/KBoard/Controller/AddNewCategory.swift
  KBoard/KBoard/Controller/CategoryListViewController.swift
  KBoard/KBoard/Controller/CustomTableCell.swift
  KBoard/KBoard/Model/KBoardDate.swift
  KBoard/KBoard/SupportFiles/SceneDelegate.swift
Labels: feat💥, 노엘 😎

#23 Merge: #5 K-pop Slang - WordListView, WordCustomCell 제작 ( ver. 2.0 )
  KBoard/KBoard.xcodeproj/project.pbxproj
  KBoard/KBoard/Model/WordModel.swift
  KBoard/KBoard/View/WordCustomCell.swift
  KBoard/KBoard/View/WordListView.swift
Labels: feat💥, 니로 🚘, UI🌉

#25 Merge: #5 K-pop Slang - WordListView, WordCustomCell 제작 (Github 브랜치 이슈로 인한 오류 수정)
  KBoard/KBoard.xcodeproj/project.pbxproj
  KBoard/KBoard/Model/WordModel.swift
  KBoard/KBoard/View/WordCustomCell.swift
  KBoard/KBoard/View/WordListView.swift
Labels: 니로 🚘, !HOTFIX 🔥

#26 Merge: !HOTFIX - "기존 wordDetail Usage, Related 합침"
  KBoard/KBoard.xcodeproj/project.pbxproj
  KBoard/KBoard/Controller/WordDetailViewController.swift
  KBoard/KBoard/View/WordDetailViewUIComponent/RelatedWordsView.swift
  KBoard/KBoard/View/WordDetailViewUIComponent/UsageContextView.swift
  KBoard/KBoard/View/WordDetailViewUIComponent/WordUsageView.swift
Labels: 윌🌊, !HOTFIX 🔥

#27 Merge: !HOTFIX - "기존 CategoryListViewController / AddNewCategory 합침"
  KBoard/KBoard/Controller/AddNewCategory.swift
  KBoard/KBoard/Controller/CategoryListViewController.swift
  KBoard/KBoard/Controller/CustomTableCell.swift
  KBoard/KBoard/Model/KBoardData.swift
Labels: !HOTFIX 🔥

#37 Merge: Feat: "WordDetailView cardShadow() 만듬"
  KBoard/KBoard/Utils/Extension/View+Extension.swift
  KBoard/KBoard/View/WordDetailViewUIComponent/RelatedWordsView.swift
  KBoard/KBoard/View/WordDetailViewUIComponent/WordDescriptionView.swift
  KBoard/KBoard/View/WordDetailViewUIComponent/WordUsageView.swift
Labels: feat💥, 윌🌊

#39 Merge: "Feat: 즐겨찾기 클릭시 카테고리 선택할 수 있는 모달 구현"
  KBoard/KBoard.xcodeproj/project.pbxproj
  KBoard/KBoard/Controller/AddCategoryModalViewController.swift
  KBoard/KBoard/Controller/WordDetailViewController.swift
  KBoard/KBoard/View/WordDetailViewUIComponent/WordDescriptionView.swift
Labels: feat💥, 윌🌊

#41 Merge: "Feat: Category List 편집하기 기능 구현" #36
  KBoard/KBoard/Controller/AddNewCategory.swift
  KBoard/KBoard/Controller/CategoryListViewController.swift
  KBoard/KBoard/Controller/CustomTableCell.swift
  KBoard/KBoard/Utils/Extension/View+Extension.swift
Labels: feat💥, 노엘 😎

#40 Merge: #18 K-pop Slang - category list view, CollectionCustomCell 제작
  KBoard/KBoard.xcodeproj/project.pbxproj
  KBoard/KBoard/Controller/DictionaryViewController.swift
  KBoard/KBoard/View/DictionaryViewUIComponent/CollectionCustomCell.swift
  KBoard/KBoard/View/DictionaryViewUIComponent/WordCategoryListView.swift
  KBoard/KBoard/View/DictionaryViewUIComponent/WordCustomCell.swift
  KBoard/KBoard/View/DictionaryViewUIComponent/WordListView.swift
Labels: feat💥, 니로 🚘, UI🌉

#42 Merge: "Feat: Dynamic button size in CustomKeyboard" #35
  KBoard/CustomKeyboard/Extension.swift
  KBoard/CustomKeyboard/KeyboardViewController.swift
  KBoard/KBoard.xcodeproj/project.pbxproj
Labels: feat💥, 진 😊, UI🌉

#43 WordList View
  KBoard/KBoard.xcodeproj/project.pbxproj
  KBoard/KBoard/Controller/MyBoard/CategoryViewController.swift
  KBoard/KBoard/Utils/Constants.swift
  KBoard/KBoard/Utils/Extension/Color+Extension.swift
  KBoard/KBoard/Utils/Extension/View+Extension.swift
  KBoard/KBoard/View/CategoryViewUIComponent/CategoryCollectionHeaderView.swift
  KBoard/KBoard/View/CategoryViewUIComponent/CategoryCollectionViewCell.swift
  KBoard/KBoard/View/DictionaryViewUIComponent/CollectionCustomCell.swift
  KBoard/KBoard/View/DictionaryViewUIComponent/WordCategoryListView.swift
Labels: feat💥

#48 Merge: #45 K-pop Slang - 상단 헤더 바 UI 제작
  KBoard/KBoard.xcodeproj/project.pbxproj
  KBoard/KBoard/Controller/KPopSlang/DictionaryViewController.swift
  KBoard/KBoard/View/KPopSlang/DictionaryViewUIComponent/DictionaryHeaderView.swift
  KBoard/KBoard/View/KPopSlang/DictionaryViewUIComponent/UpperHeaderView.swift
Labels: feat💥, 니로 🚘, UI🌉

#46 Merge Feat: 단어 List 순서 수정 및 삭제 기능 구현
  KBoard/KBoard.xcodeproj/project.pbxproj
  KBoard/KBoard/Controller/MyBoard/CategoryViewController.swift
  KBoard/KBoard/Utils/Constants.swift
  KBoard/KBoard/View/MyBoard/CategoryTableViewCell.swift
  KBoard/KBoard/View/MyBoard/CategoryViewUIComponent/CategoryCollectionHeaderView.swift
  KBoard/KBoard/View/MyBoard/CategoryViewUIComponent/CategoryCollectionViewCell.swift
Labels: feat💥, 규🏋️

#51 Merge: #47 K-pop Slang - Sticky Header View 구현
  KBoard/KBoard/Controller/KPopSlang/DictionaryViewController.swift
Labels: feat💥, 니로 🚘, UI🌉
