Repository DeveloperAcademy-POSTECH/MC3-Team2-Ddoongs, pull requests merged in 2022-08, with the labels that each got.

#54 Merge: AddNewCategory 텍스트필드 UI 및 중복체크 유효성검사 구현 #50
  KBoard/KBoard/Controller/MyBoard/CategoryListViewController.swift
  KBoard/KBoard/View/MyBoard/AddNewCategory.swift
  KBoard/KBoard/View/MyBoard/CustomTableCell.swift
Labels: feat💥, 노엘 😎

#57 Merge: Feat/56 alert same word
  KBoard/KBoard/Controller/MyBoard/AddWordViewController.swift
Labels: 윌🌊

#61 Merge: #60 SearchBar 에서 단어 검색 시 TableView 로 결과값 출력
  KBoard/KBoard/Controller/KPopSlang/DictionaryViewController.swift
  KBoard/KBoard/Model/WordModel.swift
  KBoard/KBoard/View/KPopSlang/DictionaryViewUIComponent/DictionaryHeaderView.swift
Labels: feat💥, 니로 🚘

#65 Merge: #34, #63, #64, #65 Add features to keyboardUI
  KBoard/CustomKeyboard/CollectionViewCell.swift
  KBoard/CustomKeyboard/KeyboardViewController.swift
  KBoard/KBoard.xcodeproj/project.pbxproj
Labels: feat💥, UI🌉
